# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5iB_NmtRNcrDVJ9wXHwYjNWZoluBsr4
"""

# STEP 1: Install packages (Python 3.12 compatible)
!pip install -q openai-whisper transformers torch soundfile
!apt-get update -qq && apt-get install -y -qq ffmpeg

print("✅ Installation complete")

# STEP 2: Import libraries
import whisper
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import base64
from IPython.display import Audio, display, Javascript
from google.colab import output
import wave
import json
import numpy as np
import time

print("✅ Imports ready")

# STEP 3: Configure Gemini API
from google.colab import userdata
import google.generativeai as genai

try:
    API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=API_KEY)
    print("✅ Gemini configured.")
except Exception as e:
    print("❌ Key not found. Please set GOOGLE_API_KEY in Secrets.")
    API_KEY = None

# STEP 4: Audio Recording Script
RECORD_SCRIPT = """
async function record() {
  let stream;
  try {
    stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  } catch(e) {
    return { error: "Permission denied: " + e.message };
  }

  const track = stream.getAudioTracks()[0];
  if (!track) return { error: "No audio track" };

  const audioContext = new (window.AudioContext || window.webkitAudioContext)();
  const source = audioContext.createMediaStreamSource(stream);
  const analyser = audioContext.createAnalyser();
  analyser.fftSize = 256;
  source.connect(analyser);
  const dataArray = new Uint8Array(analyser.frequencyBinCount);

  const recorder = new MediaRecorder(stream);
  const chunks = [];
  recorder.ondataavailable = e => chunks.push(e.data);
  recorder.start();

  let maxVolume = 0;
  const interval = setInterval(() => {
    analyser.getByteFrequencyData(dataArray);
    const avg = dataArray.reduce((a, b) => a + b, 0) / dataArray.length;
    if (avg > maxVolume) maxVolume = avg;
  }, 100);

  await new Promise(r => setTimeout(r, 10000));
  recorder.stop();
  clearInterval(interval);
  await new Promise(r => setTimeout(r, 500));
  audioContext.close();

  const blob = new Blob(chunks, { type: 'audio/wav' });
  const reader = new FileReader();
  reader.readAsDataURL(blob);
  return new Promise(r => reader.onloadend = () => r({
    audio: reader.result.split(',')[1],
    volume: Math.round(maxVolume)
  }));
}
record();
"""

print("🎤 Recording 10 seconds... Speak clearly (Urdu/English/Hindi).")
result = output.eval_js(RECORD_SCRIPT)

# STEP 5: Process audio input
transcribed_text = ""
detected_lang = "en"
confidence_score = 0.0

if "error" in result:
    print("❌", result["error"])
    transcribed_text = input("✏️ Type your message: ")
    detected_lang = "en"
else:
    volume = result.get("volume", 0)
    print(f"📊 Volume: {volume}")

    if volume < 10:
        print("🔇 Very quiet – please speak louder.")
        transcribed_text = input("✏️ Type your message: ")
        detected_lang = "en"
    else:
        # Save audio file
        with open("/tmp/voice_input.wav", "wb") as f:
            f.write(base64.b64decode(result["audio"]))
        print("✅ Audio saved.")
        display(Audio("/tmp/voice_input.wav"))

# STEP 6: Transcribe with Whisper
import whisper
import numpy as np

print("🔄 Loading Whisper (medium)...")
model = whisper.load_model("medium")

print("🎯 Transcribing...")
whisper_result = model.transcribe(
    "/tmp/voice_input.wav",
    fp16=False,
    verbose=True,
    word_timestamps=True
)

transcribed_text = whisper_result["text"]
detected_lang = whisper_result["language"]

# --- Confidence Matrix ---
segments = whisper_result.get("segments", [])
avg_logprobs = [seg.get("avg_logprob", 0) for seg in segments]
no_speech_probs = [seg.get("no_speech_prob", 0) for seg in segments]

overall_avg_logprob = np.mean(avg_logprobs) if avg_logprobs else 0
overall_no_speech_prob = np.mean(no_speech_probs) if no_speech_probs else 0

confidence_score = min(1.0, max(0.0, (overall_avg_logprob + 1.0) / 2.0))

print("\n📝 TRANSCRIPTION:")
print(transcribed_text)
print(f"🌐 Detected language: {detected_lang}")

print("\n📊 WHISPER CONFIDENCE MATRIX")
print("-" * 50)
print(f"🔹 Overall Confidence Score (0–1):  {confidence_score:.2f}")
print(f"🔹 Average Log-Probability:         {overall_avg_logprob:.2f}")
print(f"🔹 No-Speech Probability:           {overall_no_speech_prob:.2f}")
print("-" * 50)
for i, seg in enumerate(segments):
    seg_conf = min(1.0, (seg.get('avg_logprob', 0) + 1.0) / 2.0)
    text_preview = seg['text'][:30] + "..." if len(seg['text']) > 30 else seg['text']
    print(f"Segment {i+1}: '{text_preview}' → Confidence: {seg_conf:.2f}")
print("=" * 50)

# Manual correction
correct = input("\n✏️ Is this transcription correct? (y/n): ").strip().lower()
if correct != 'y':
    transcribed_text = input("✏️ Type the correct text: ")
    detected_lang = input("🌐 Enter language (ur/en/hi): ").strip().lower() or detected_lang
    confidence_score = 1.0
    print("✅ Manual override – confidence set to 1.0.")

# STEP 7: Semantic Analysis with Gemini
import json

try:
    if API_KEY:
        model_gemini = genai.GenerativeModel('gemini-2.5-flash')

        prompt = f"""
You are an AI assistant that analyzes Urdu/English/Hinglish text.

Transcription: "{transcribed_text}"
Detected language: {detected_lang}
Whisper confidence: {confidence_score:.2f}

Your task:
1. Provide a friendly, context-aware reply.
2. Extract intent, grammatical structure (Subject, Verb, Object, Noun Phrases).
3. Return a confidence score (0.0 to 1.0) for each of:
   - "transcription_confidence": based on Whisper's score + how coherent the text is.
   - "grammar_confidence": how sure you are about the SVO extraction.
   - "intent_confidence": how sure you are about the intent.
   - "reply_confidence": how sure you are that your reply is appropriate.

Return ONLY a JSON object with this structure:
{{
    "reply": "...",
    "intent_summary": "...",
    "language": "ur/en/hi",
    "confidence": {{
        "transcription_confidence": 0.0,
        "grammar_confidence": 0.0,
        "intent_confidence": 0.0,
        "reply_confidence": 0.0
    }},
    "grammatical_analysis": {{
        "subject": "...",
        "helping_verb": "...",
        "verb": "...",
        "object": "...",
        "noun_phrases": ["..."],
        "other_entities": {{}}
    }},
    "actions": [
        {{"verb": "action", "target": "target"}}
    ]
}}
"""

        response = model_gemini.generate_content(
            prompt,
            generation_config={
                "temperature": 0.2,
                "response_mime_type": "application/json"
            }
        )

        try:
            data = json.loads(response.text)
            print("\n🤖 GEMINI REPLY:")
            print(data.get("reply", "No reply generated."))

            print("\n📊 GEMINI CONFIDENCE MATRIX")
            print("-" * 50)
            conf = data.get("confidence", {})
            print(f"🔹 Transcription Confidence: {conf.get('transcription_confidence', 0):.2f}")
            print(f"🔹 Grammar Extraction Conf.: {conf.get('grammar_confidence', 0):.2f}")
            print(f"🔹 Intent Understanding:     {conf.get('intent_confidence', 0):.2f}")
            print(f"🔹 Reply Appropriateness:    {conf.get('reply_confidence', 0):.2f}")
            print("-" * 50)

            print("\n--- DEEP ANALYSIS ---")
            print(json.dumps(data, indent=2, ensure_ascii=False))

        except Exception as e:
            print("❌ Error parsing Gemini response:", e)
            print("Raw:", response.text)
    else:
        print("⏩ Skipping analysis (no API key).")

except Exception as e:
    print("❌ Error:", e)

# STEP 8: Text-to-Speech with Gemini TTS
try:
    if API_KEY:
        # Import required modules
        from google import genai as genai_client
        from google.genai import types

        print("🎧 Generating TTS...")

        client = genai_client.Client(api_key=API_KEY)
        response = client.models.generate_content(
            model='gemini-2.5-flash-preview-tts',
            contents=transcribed_text,
            config=types.GenerateContentConfig(
                response_modalities=['AUDIO'],
                speech_config=types.SpeechConfig(
                    voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name='Kore')
                    )
                )
            )
        )

        # Extract audio data
        audio_data = response.candidates[0].content.parts[0].inline_data.data

        # Save as WAV file
        with wave.open("output.wav", "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(24000)
            wf.writeframes(audio_data)

        print("🎧 Gemini TTS ready.")
        display(Audio("output.wav", autoplay=True))
    else:
        print("⏩ Skipping TTS (no API key).")

except Exception as e:
    print("⚠️ TTS error:", e)

# STEP 9: Complete pipeline function
def run_bilingual_compiler():
    """Run the complete bilingual compiler pipeline"""

    print("=" * 60)
    print("🚀 URDU-ENGLISH BILINGUAL COMPILER")
    print("=" * 60)

    # Step 1: Record audio
    print("\n🎤 Recording 10 seconds... Speak clearly!")
    result = output.eval_js(RECORD_SCRIPT)

    if "error" in result:
        print("❌", result["error"])
        transcribed_text = input("✏️ Type your message: ")
        detected_lang = "en"
        confidence_score = 1.0
    else:
        volume = result.get("volume", 0)
        print(f"📊 Volume: {volume}")

        if volume < 10:
            print("🔇 Very quiet – please speak louder.")
            transcribed_text = input("✏️ Type your message: ")
            detected_lang = "en"
            confidence_score = 1.0
        else:
            with open("/tmp/voice_input.wav", "wb") as f:
                f.write(base64.b64decode(result["audio"]))
            print("✅ Audio saved.")
            display(Audio("/tmp/voice_input.wav"))

            # Transcribe with Whisper
            model = whisper.load_model("medium")
            whisper_result = model.transcribe(
                "/tmp/voice_input.wav",
                fp16=False,
                verbose=True,
                word_timestamps=True
            )

            transcribed_text = whisper_result["text"]
            detected_lang = whisper_result["language"]

            # Confidence calculation
            segments = whisper_result.get("segments", [])
            avg_logprobs = [seg.get("avg_logprob", 0) for seg in segments]
            overall_avg_logprob = np.mean(avg_logprobs) if avg_logprobs else 0
            confidence_score = min(1.0, max(0.0, (overall_avg_logprob + 1.0) / 2.0))

    # Display transcription
    print(f"\n📝 Transcription: {transcribed_text}")
    print(f"🌐 Language: {detected_lang}")
    print(f"📊 Confidence: {confidence_score:.2f}")

    # Semantic analysis with Gemini
    if API_KEY:
        model_gemini = genai.GenerativeModel('gemini-2.5-flash')

        prompt = f"""
You are an AI assistant analyzing Urdu/English/Hinglish text.

Transcription: "{transcribed_text}"
Detected language: {detected_lang}
Confidence: {confidence_score:.2f}

Analyze and return JSON with:
- reply (friendly response)
- intent_summary
- language
- confidence scores
- grammatical_analysis (subject, helping_verb, verb, object, noun_phrases)
- actions
"""

        response = model_gemini.generate_content(
            prompt,
            generation_config={
                "temperature": 0.2,
                "response_mime_type": "application/json"
            }
        )

        try:
            data = json.loads(response.text)
            print("\n🤖 Gemini Reply:", data.get("reply", "No reply"))
            print(f"🎯 Intent: {data.get('intent_summary', 'Unknown')}")

            # TTS
            print("\n🎧 Generating TTS...")
            client = genai_client.Client(api_key=API_KEY)
            tts_response = client.models.generate_content(
                model='gemini-2.5-flash-preview-tts',
                contents=data.get("reply", transcribed_text),
                config=types.GenerateContentConfig(
                    response_modalities=['AUDIO'],
                    speech_config=types.SpeechConfig(
                        voice_config=types.VoiceConfig(
                            prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name='Kore')
                        )
                    )
                )
            )

            audio_data = tts_response.candidates[0].content.parts[0].inline_data.data
            with wave.open("output.wav", "wb") as wf:
                wf.setnchannels(1)
                wf.setsampwidth(2)
                wf.setframerate(24000)
                wf.writeframes(audio_data)

            print("✅ TTS complete!")
            display(Audio("output.wav", autoplay=True))

        except Exception as e:
            print("❌ Error:", e)
    else:
        print("⏩ Skipping Gemini analysis (no API key).")

    print("\n" + "=" * 60)
    print("✅ Compiler execution complete!")
    print("=" * 60)